apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qamykwf4h-python 
  janus-idp.io/tekton: qamykwf4h-python
  backstage.io/kubernetes-id: qamykwf4h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qamykwf4h-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml